#!/bin/bash

function check_okay {
	if [ $? -ne 0 ]
	then
		exit 1
	fi
}


function do_one {
	cp $1 inlist
	check_okay
	rm -rf $2
	echo 'run' $1
	./rn1
	check_okay
  if [ ! -r $2 ]
  then
  	echo
  	echo "******************************************************************"
  	echo 'failed to create' $2 'when running' $1
  	echo "******************************************************************"
  	echo
  	exit 1
  fi
  echo
  echo 'finished' $1
  echo
	echo '***'
	echo '***'
	echo '***'
	echo '***'
	echo '***'
	echo '***'
	echo
}

date "+DATE: %Y-%m-%d%nTIME: %H:%M:%S"
do_one inlist_create_1.0_MJ_10.0_ME_2.0_RJ planet_create_0.9685_MJ_2.0_RJ.mod
do_one inlist_core_1.0_MJ_10.0_ME_2.0_RJ planet_core_1.0_MJ_10.0_ME_2.0_RJ.mod
do_one inlist_evolve_1.0_MJ_10.0_ME_2.0_RJ planet_evolve_1.0_MJ_10.0_ME_2.0_RJ.mod
date "+DATE: %Y-%m-%d%nTIME: %H:%M:%S"

echo 'finished all inlists for make_planets'

